### ISSUE TITLE
Not to complain, but

### ISSUE THREAD

**Issue by carnotweat** [Dragon2fly/vpngate-with-proxy#19]
It is a wrapper on top of openvpn.
Plus it breaks more than it works.

**Comment by Dragon2fly** [comment]
Hi @carnotweat 

Thanks for your comment.

> It is a wrapper on top of openvpn.
Why shouldn't it wrap openvpn? Invent a new vpn protocol is not something can be done by one man. Plus security threat and another dozen bugs. I don't intend to reinvent the wheel.

> Plus it breaks more than it works.
You should point out where and how it breaks so that it could be fixed. In the best case, you can fix it and make the pull request. Current the my time for this project is quite limited. I do have other work to do for a living, too :)
