### ISSUE TITLE
Not linux, but Debian

### ISSUE THREAD

**Issue by evadogstar** [Dragon2fly/vpngate-with-proxy#2]
Unfortunately, It's only Debian client, not linux :( It does not work on fedora :( and request at least resolvconf to be installed (Debial package)

**Comment by Dragon2fly** [comment]
@evadogstar Thank you for testing my program. As you have noticed that this program only works on Debian based OS, not Redhat based. Making it work on Fedora requires a lot of code changing and testing. For started, could you tell me which Fedora version are you using? And why is resolvconf requested?

**Comment by Dragon2fly** [comment]
@evadogstar I've just tested it on Fedora25 (64bit). In the source code, replacing only `apt-get` into `dnf` and then it work just fine! Not so many code changed as I thought! `Openvpn` and `Git` are already there on Fedora but not Python2.7, that's just weird compared to Ubuntu.

When it didn't work for you. Exactly what did you do and what is the error message?

**Comment by evadogstar** [comment]
@Dragon2fly Fedora24
I start it with `./run cli` then I get the error message about lack of dependencies `resolvconf` Then it try to install it on Debian way :) 
Is `resolvconf` used for testing DNS only?

**Comment by Dragon2fly** [comment]
@evadogstar I rechecked the `cli` code. `resolvconf` was there from the first time I wrote the script. It is used in `userscript` to change the `DNS` in the way that you described. But then I found it unstable. There were many times that it didn't reset the DNS as expected. So I decided to make my code handle the DNS itself. `resolvconf` is no longer needed. I'm sorry for not deleting it out of the new code.

I updated the code. Now Fedora/CentOS user only need to install `python2.7 `. The rest dependencies should be automatically install without error. Automatically select  `apt-get` on Debian based and `yum/dnf` on Redhat based OS.

About executing a `userscript`, since I didn't trust OpenVPN to do the job, I would like to let my code handle it too. Do you have an example `script file` that I can test with?

About notification, the code already provided an `app indicator` which also has a nice `notification` itself. Sadly, it required `gir1.2-appindicator` package to make this code `from gi.repository import AppIndicator3` run without error. I seem can not install it on Fedora.

I will make the code use `notify-send` if `app indicator` failed later.

Can use test both `cli` and `tui` again to see if there is any error? 
Thank you.

**Comment by evadogstar** [comment]
@Dragon2fly Thanks for fast update. I will test it now, but about the up/down script as "advanced option". Please, If possible add this possibility. I'm on Qubes (with Fedora template) and as already expected my system and config need some additional actions to be executed on connect/disconnect to prevent vpn leaks. 

The documentation page where anti leak script is available and described perfectly. Paragraph: 
`Set up a ProxyVM as a VPN gateway using iptables and CLI scripts` Step 3-5. But it's for my system. On the comment below I will try to describe the same for any "regular" system way. 

Again. Thank you!

**Comment by evadogstar** [comment]
@Dragon2fly  Oh. Sorry. I started re-write the original anti-leak script from Qubes and have troubles. I'm not advanced unix user to rewrite iptables rules from Qubes example for any regular system unix based. My system already have some specific  `PR-QBS` group at iptables to re-translate DNS request as a bridge. But it's not necessary for testing

Below up/down script for test purposes. It do nothing only notify. 

~/vpn-handler.sh:
```
#!/bin/bash
set -e
export PATH="$PATH:/usr/sbin:/sbin"

case "$1" in

up)
    su - -c 'notify-send "$(hostname): LINK IS UP." --icon=network-idle' user
else
    su - -c 'notify-send "$(hostname): LINK UP, NO DNS!" --icon=dialog-error' user
fi

;;
down)
su - -c 'notify-send "$(hostname): LINK IS DOWN !" --icon=dialog-error' user
;;
esac
```
Then `sudo chmod +x vpn-handler.sh`

Then add to downloaded config:
```
`script-security 2
up '~/vpn-handler.sh up'
down '~/vpn-handler.sh down'`
```

**Comment by Dragon2fly** [comment]
@evadogstar I updated my program again. You just need to modify the `user_script.sh` file to do your jobs, no need to mess with `config.ini`.

`OpenVPN` required `root` privilege to run, thus my program must acquire it too. Consequently, all script called by my program will inherit `root`, so does `user_script.sh`.

> is it possible to also manage groups of subproccess from python to add the possibility to start all requested internet programs from this group if need (openvpn, ping, etc)?

Yes, it is possible. You can always write another `starter.py` or `starter.sh` to do such a kind of action. But if you only need to call them **after** vpn tunnel is establish, better to leave them to `user_script.sh`.

Again, I hope you can test the updated program and report if it work or not.
Thank you.

**Comment by evadogstar** [comment]
Thanks :) It works! But I need to do more tests. 

Now, I see only one problem:
`post_action('down')` need to be at `except KeyboardInterrupt:` to execute `down` when tunnel terminated by user.

**Comment by Dragon2fly** [comment]
> post_action('down') need to be at except `KeyboardInterrupt`: to execute down when tunnel terminated by user CTLR+C.

Hasn't it already worked that way? No matter how the vpn tunnel is terminated, `post_action` is always executed.

> Is it possible to export "DNS list" from your script to `user_script.sh` as environment variable?
`$vpn_dns` with values of dns "8.8.8.8 7.7.7.7 8.8.8.8" ?

DNS values is stored in `config.ini`. If you want to change it within `user_script.sh`, disable the `fix_dns ` in `config.ini`, then use your `$vpn_dns` variable. Another way is that you make another `starter` script which will change the `config.ini`'s `dns` according to the users / usergroups...

Currently, since all settings are must be store in `config.ini`, I prefer the way from main program to `user_script` to be a `one-way` route.

**Comment by evadogstar** [comment]
> Hasn't it already worked that way? No matter how the vpn tunnel is terminated, post_action is always executed.
I retest this again. I'm looking for `notify-send` window, it does not show on `ctrl+c`, but (sorry) down script executed. I see "Called Down script" message. All is okey with this.

> Currently, since all settings are must be store in config.ini, I prefer the way from main program to user_script to be a one-way route.

Maybe it's my bad English or some misunderstanding :) But I'm also offered to get DNS from the main program and per-define environment variable with DNS list to `user_script` when it called. Then `user_script` can be used with "DNS fix enabled". You "DNS fix" only add new dns. But need to allow access to them at firewall with `user_script` if our system use firewall to prevent leaks. 

Sorry for trouble you :)

**Comment by Dragon2fly** [comment]
Sorry for misunderstanding you. So you need the DNS **appeared** in the `user_script.sh` so that you can inform your **firewall** to **allow connections** to them. It is better not to change the source code of main program since other people don't have that need. Instead, let do entire job within `user_script.sh` only. The below code will parse DNS from `config.ini`, remove `,` and store the result in `dns` variable.

``` bash
    dns=$(cat config.ini | grep -o -P '(?<=^dns = ).*')
    dns="${dns//,/}"
    echo $dns
```

Then, just use your `dns` to do what ever needed with your firewall.

Perhaps, you should write about your use-case somewhere for other people to follow.

Thanks :)

**Comment by evadogstar** [comment]
Thanks! I will test it soon! 
It will be used with QubesOS  as ProxyVM (VpnVM) :)

**Comment by evadogstar** [comment]
Perfect. Thank you! Now it work fine :+1:

**Comment by Dragon2fly** [comment]
Feel free to do it :) . This issue is about running on Redhat based OS and has been solved. I'll close it now.
