### ISSUE TITLE
how to get server list? windows and linux difference server list?

### ISSUE THREAD

**Issue by nextnaro** [Dragon2fly/vpngate-with-proxy#26]
windows get thai list.
![image](https://user-images.githubusercontent.com/31925501/44738729-6b2db800-ab28-11e8-9792-322eb63a88f0.png)

linux no thai server list
![image](https://user-images.githubusercontent.com/31925501/44738793-931d1b80-ab28-11e8-8def-64029ea2308c.png)

**Comment by Dragon2fly** [comment]
Hello @nextnaro ,

> linux no thai server list
This depends on which countries are in the server list the program received. 
Could you try `th` instead of 'thai'?

> how to get server list?
The server list is downloaded from the [api url](http://www.vpngate.net/api/iphone/). The list is created dynamically by the server. If you add it's mirrors to `config.ini` file, you may get a better chance to catch Thai server on the list.
