### ISSUE TITLE
unexpected exit after changing country at cli

### ISSUE THREAD

**Issue by evadogstar** [Dragon2fly/vpngate-with-proxy#32]
After changing country at cli (5 option) and begin searching for servers vpngate-with-proxy exit with the following error. 

Also question related to the 5 option. Is it possible to add opportunity to use country list at step 5 ( "jp, kr, us") as value ?

```
  File "vpnproxy_cli.py", line 485, in <module>
    sort_by = cfg.sort.values()[0]
TypeError: 'dict_values' object is not subscriptable

```

**Comment by Dragon2fly** [comment]
Sorry for the error of cli. I missed it out during the conversion from py2 to py3 three months ago.
Since I've fixed it, could you test if there are still errors somewhere?

Multiple countries filter has been working as a side effect on `tui`, now it also works with `cli` version.
From now on, it is an official feature 😄 

You don't use a comma as separator, you use a vertical bar `|`. 
The input string is passed directly as a regular expression to the filter. So there shouldn't be spaces around the bar!
As your example, the input string is: `jp|kr|us`

Have a nice weekend 😃

**Comment by evadogstar** [comment]
@Dragon2fly Tested! Now all working fine! Thank you! :-)

**Comment by Dragon2fly** [comment]
Glad to hear that! I am closing this issues for now.
