### ISSUE TITLE
Cannot connect to vpngate mirror sites

### ISSUE THREAD

**Issue by Rusiann** [Dragon2fly/vpngate-with-proxy#35]
vpngate.net is blocked by my ISP. There are mirror sites which can be accessible by my browser but I can't connect with vpngate-with-proxy. Here is the log of vpn.
>Sat Feb  5 20:27:05 2022: Vpngate with proxy is started
 using gate: http://www.vpngate.net
ConnectionTimeout
 Connection to gate http://www.vpngate.net failed
 using gate: http://213.136.92.167:13182
ConnectionError
 Connection to gate http://213.136.92.167:13182 failed
 using gate: http://78.142.193.246:33304
ConnectionError
 Connection to gate http://78.142.193.246:33304 failed
 using gate: http://172.107.219.42:32685
ConnectionError
 Connection to gate http://172.107.219.42:32685 failed
 using gate: http://222.255.11.117:54621
ConnectionError
 Connection to gate http://222.255.11.117:54621 failed
 using gate: http://i118-27-48-67.vpngate-sv.d.rspnet.jp:7458
ConnectionError
 Connection to gate http://i118-27-48-67.vpngate-sv.d.rspnet.jp:7458 failed
 using gate: http://118.105.213.20:23041
ConnectionError
 Connection to gate http://118.105.213.20:23041 failed
 Failed to get VPN servers data
 Check your network setting and proxy

**Comment by Dragon2fly** [comment]
Hi, can you give me more information?
1. What browser are you using? 
2. Do you directly connect to the Internet or through a proxy?

**Comment by Rusiann** [comment]
I am using Firefox. I tested mirror links with Edge too and the links work. Also I directly connect to the internet. I am using Linux Mint 20.03.

**Comment by Dragon2fly** [comment]
Oh, just realize that those mirrors don't cache database csv file. 
They all point back to the `http://www.vpngate.net/api/iphone/` which is already blocked. 
So none of them will work.

Since you directly connect to the internet, then you just need to add a proxy into `vpngate-with-proxy` by pressing `F2` for `tui` version.
The proxy will allow it to download the csv file. 
You then, turn off the proxy (`F2`)  before connecting to any vpn server.

※ For list of proxies, you could easily search `free proxy list` on google.

**Comment by Rusiann** [comment]
Thanks, I've been using a vpn as alternative to find vpngate servers then close it to connect to vpngate. I guess this is another way to connect to vpngate servers. If only there was a mirror sites that actually fetches from main site, huh...

**Comment by Dragon2fly** [comment]
I'm glad that you find another workaround too. 
I going to close this ticket.
If you have any issues, feel free to open another one,
